### ISSUE TITLE
Solving mlflow=2.12.2=py39hb3b8efb_0 takes a lot of time

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [conda/rattler#684] opened 2024-05-27 15:42 UTC
Hello, while trying rattler (via py-rattler), I noticed that some packages take ages to resolve. For example:

```python
>>> import rattler
>>> import asyncio
>>> asyncio.run(rattler.solve(['main'], ['mlflow=2.12.2=py39hb3b8efb_0'], platforms=['osx-arm64', 'noarch']))
```

`mlflow=2.12.2=py39hb3b8efb_0` is fast to resolve with conda-libmamba-solver.

The same is true with all these packages (on osx-arm64):
* `orange3=3.36.2=py39h46d7db6_0`
* `ray-dashboard=2.6.3=py39hca03da5_2`
* `ray-default=2.6.3=py39hca03da5_2`
* `spark-nlp=5.1.2=py39hca03da5_0`
* `spyder=5.5.1=py38hca03da5_0`
* `spyder=5.5.1=py39hca03da5_0`
* `spyder=5.5.1=py310hca03da5_0`
* `streamlit-faker=0.0.2=py39hca03da5_0`

**Comment by baszalmstra** [comment] 2024-05-27 16:12
Thanks for these! I can confirm that these are horribly slow and instant with libsolv. We will investigate!

**Comment by JeanChristopheMorinPerso** [comment] 2024-05-27 16:19
Ok, thanks for confirming! If you are curious, I found these by iterating through every single record in the channel and trying to resolve them individually.

**Comment by baszalmstra** [comment] 2024-05-28 07:37
I've found a performance improvement that fixes these cases (they resolve instantly) but makes all other solves about 50% slower... Need more investigation. 😅

**Comment by wolfv** [comment] 2024-05-31 11:04
We found a solution for this case by changing our selection heuristic. Currently we are deciding packages with few options first, in order to minimize backtracking. But it seems to not play well with Python constraints since apparently we are doing excessive backtracking. 

If we reverse the heuristic, things are super fast (ie. decide packages with many options first). 

Did you write some kind of benchmark script @JeanChristopheMorinPerso? I think we'll adjust the heuristic, but it would be great to have more extensive benchmarks to check that we don't introduce big regressions.

For the "fix", I just changed the `<` to `>` in this line: https://github.com/mamba-org/resolvo/blob/56fa93de027f483223c6525671e243d89cd805fe/src/solver/mod.rs#L761

**Comment by baszalmstra** [comment] 2024-10-03 19:20
We have landed some pretty [significant](https://github.com/mamba-org/resolvo/pull/66) [improvements](https://github.com/mamba-org/resolvo/pull/67) to the solver in the latest version (py-rattler 0.7.1).

| spec | time to solve |
|-----|--|
| mlflow=2.12.2=py39hb3b8efb_0         | 102 ms |
| orange3=3.36.2=py39h46d7db6_0        | 395 ms |
| ray-dashboard=2.6.3=py39hca03da5_2   | 80 ms  |
| ray-default=2.6.3=py39hca03da5_2     | 87 ms  |
| spark-nlp=5.1.2=py39hca03da5_0       | 159 ms |
| spyder=5.5.1=py38hca03da5_0          | 193 ms |
| spyder=5.5.1=py39hca03da5_0          | 246 ms |
| spyder=5.5.1=py310hca03da5_0         | 112 ms |
| streamlit-faker=0.0.2=py39hca03da5_0 | 80 ms  |

This is not to say there will still be slow cases but if you look at [the latest benchmarks](https://github.com/mamba-org/resolvo/pull/67) the number of them has significantly decreased. 

I'm going to close this issue for now, but feel free to reopen if you find more difficult cases.

**Closed by baszalmstra** 2024-10-03 19:20 UTC

**Comment by JeanChristopheMorinPerso** [comment] 2024-10-07 14:58
Thanks @baszalmstra for the update!
